module ExploitDataProxy

  def report_exploit_attempt(host, opts)
    begin
      data_service = self.get_data_service()
      data_service.report_exploit_attempt(host, opts)
    rescue  Exception => e
      puts"Call to  #{data_service.class}#report_exploit_attempt threw exception: #{e.message}"
    end
  end

  def report_exploit_failure(opts)
    begin
      data_service = self.get_data_service()
      data_service.report_exploit_failure(opts)
    rescue  Exception => e
      puts"Call to  #{data_service.class}#report_exploit_failure threw exception: #{e.message}"
    end
  end

  def report_exploit_success(opts)
    begin
      data_service = self.get_data_service()
      data_service.report_exploit_success(opts)
    rescue  Exception => e
      puts"Call to  #{data_service.class}#report_exploit_success threw exception: #{e.message}"
    end
  end
end